const REVIEWABLE_REQUESTS_CREATOR = "REVIEWABLE_REQUESTS_CREATOR";
const REVIEWABLE_REQUESTS_REMOVER = "REVIEWABLE_REQUESTS_REMOVER";

const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";
const KYC_REQUESTS_RESOURCE = "KYC_REQUESTS_RESOURCE";

const CREATE_PERMISSION = "CREATE";
const DELETE_PERMISSION = "DELETE";

const KYC_REQUESTS_DEP = "KYC_REQUESTS";

module.exports = {
  REVIEWABLE_REQUESTS_CREATOR,
  REVIEWABLE_REQUESTS_REMOVER,
  REVIEWABLE_REQUESTS_RESOURCE,
  KYC_REQUESTS_RESOURCE,
  CREATE_PERMISSION,
  DELETE_PERMISSION,
  KYC_REQUESTS_DEP,
};
