const CREATE_PERMISSION = "CREATE";
const DELETE_PERMISSION = "DELETE";
const EXECUTE_PERMISSION = "EXECUTE";

const RBAC_RESOURCE = "RBAC_RESOURCE";
const REVIEWABLE_REQUESTS_RESOURCE = "REVIEWABLE_REQUESTS_RESOURCE";

const KYC_REQUESTS_DEP = "KYC_REQUESTS";

const RequestStatus = {
  NONE: 0,
  PENDING: 1,
  ACCEPTED: 2,
  REJECTED: 3,
  DROPPED: 4,
};

module.exports = {
  CREATE_PERMISSION,
  DELETE_PERMISSION,
  EXECUTE_PERMISSION,
  RBAC_RESOURCE,
  REVIEWABLE_REQUESTS_RESOURCE,
  KYC_REQUESTS_DEP,
  RequestStatus,
};
